//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace veteriner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detay
    {
        public int id { get; set; }
        public string Hasta_ad { get; set; }
        public string foto { get; set; }
        public string Sahip_ad { get; set; }
        public string Cins { get; set; }
        public string Tani { get; set; }
    }
}
